jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: justb4/jmeter}
      run:
        path: echo
        args: ["Hello, world!"]